#!/usr/bin/env bash
# scripts/washing-machine/preflight.sh
# Runs on Mac Mini. Verifies all non-Node dependencies required for Washing Machine
# Memory Ship 1 are reachable + functional BEFORE any feature code lands.
#
# Checkpoint 0 gate: this script must exit 0 before Commit 0b starts.
#
# 7 steps (per plans/2026-04-21_washing-machine-ship-1.md Pre-flight section):
#   1. venv at ~/Projects/K2B/venv/washing-machine/ + sentence-transformers installed
#      + WASHING_MACHINE_PYTHON exported to ~/.config/k2b/washing-machine.env
#   2. sentence-transformers loads all-MiniLM-L6-v2, returns 384-dim vector
#   3. SQLite FTS5 works with the pinned interpreter
#   4. MiniMax chat reachable via scripts/minimax-json-job.sh
#   5. MiniMax VLM reachable at POST /v1/coding_plan/vlm on api.minimaxi.com
#   6. flock / mkdir dual lock pattern works (same pattern as motivations-helper.sh)
#   7. scripts/vault-query.sh search "Dr Lo Hak Keung" returns results
#
# Exit 0 = all 7 pass. Exit N = specific check failed, prints which one + fix hint.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
VENV_DIR="${HOME}/Projects/K2B/venv/washing-machine"
ENV_FILE="${HOME}/.config/k2b/washing-machine.env"
TEST_IMAGE="/tmp/preflight-test-128.png"
TEST_PROMPT="/tmp/preflight-prompt.txt"
LOCK_DIR="/tmp/k2b-preflight-lock-test"
FLOCK_LOCKFILE="/tmp/k2b-preflight-flock.lock"

# Clean up /tmp artifacts on any exit (success or fail). Preserves nothing.
cleanup() {
  rm -f "$TEST_IMAGE" "$TEST_PROMPT" "$FLOCK_LOCKFILE"
  rm -rf "$LOCK_DIR" "${LOCK_DIR}.d"
}
trap cleanup EXIT

# --- Colors ---
RED=$'\033[31m'
GREEN=$'\033[32m'
YELLOW=$'\033[33m'
RESET=$'\033[0m'

# --- Optional outer timeout wrapper (macOS ships no GNU `timeout`) ---
if command -v gtimeout >/dev/null 2>&1; then
  TIMEOUT_CMD="gtimeout"
elif command -v timeout >/dev/null 2>&1; then
  TIMEOUT_CMD="timeout"
else
  TIMEOUT_CMD=""  # rely on inner curl --max-time
fi

run_with_timeout() {
  local secs="$1"; shift
  if [[ -n "$TIMEOUT_CMD" ]]; then
    "$TIMEOUT_CMD" "$secs" "$@"
  else
    "$@"
  fi
}

pass() { echo "${GREEN}[PASS]${RESET} $*"; }
fail() { echo "${RED}[FAIL]${RESET} $*" >&2; }
info() { echo "${YELLOW}[....]${RESET} $*"; }

step_header() {
  echo
  echo "=== Step $1: $2 ==="
}

# --- Step 1: venv + sentence-transformers ---
step_header 1 "venv + sentence-transformers install"

if [[ ! -d "$VENV_DIR" ]]; then
  info "Creating venv at $VENV_DIR"
  mkdir -p "$(dirname "$VENV_DIR")"
  python3 -m venv "$VENV_DIR" || { fail "venv creation failed"; exit 1; }
fi

WASHING_MACHINE_PYTHON="${VENV_DIR}/bin/python3"

if [[ ! -x "$WASHING_MACHINE_PYTHON" ]]; then
  fail "python3 not executable at $WASHING_MACHINE_PYTHON"
  exit 1
fi

# Check sentence-transformers
if ! "$WASHING_MACHINE_PYTHON" -c "import sentence_transformers" 2>/dev/null; then
  info "sentence-transformers not installed; running pip install (this takes ~2-5 min on first run)"
  "$WASHING_MACHINE_PYTHON" -m pip install --quiet --upgrade pip || { fail "pip upgrade failed"; exit 1; }
  "$WASHING_MACHINE_PYTHON" -m pip install --quiet 'sentence-transformers>=3.0,<4' numpy || {
    fail "pip install sentence-transformers failed. If torch has no wheel for Python $(${WASHING_MACHINE_PYTHON} -c 'import sys; print(sys.version.split()[0])'), downgrade to Python 3.12 or 3.13."
    exit 1
  }
fi

# Export pinned interpreter path for other washing-machine scripts
mkdir -p "$(dirname "$ENV_FILE")"
cat > "$ENV_FILE" <<EOF
# Generated by scripts/washing-machine/preflight.sh
# Every washing-machine Python script must source this or reference \$WASHING_MACHINE_PYTHON.
export WASHING_MACHINE_PYTHON="${WASHING_MACHINE_PYTHON}"
EOF

pass "venv at $VENV_DIR; sentence-transformers installed; WASHING_MACHINE_PYTHON exported to $ENV_FILE"

# --- Step 2: sentence-transformers loads all-MiniLM-L6-v2 + 384-dim ---
step_header 2 "sentence-transformers model load"

# First run downloads the 22MB model to ~/.cache/torch/sentence_transformers/
info "Loading all-MiniLM-L6-v2 (first run downloads ~22MB to ~/.cache/torch/sentence_transformers/)"

"$WASHING_MACHINE_PYTHON" -c "
from sentence_transformers import SentenceTransformer
m = SentenceTransformer('all-MiniLM-L6-v2')
v = m.encode('doctor phone number')
assert v.shape == (384,), f'expected (384,), got {v.shape}'
print(f'embedding shape ok: {v.shape}')
" || { fail "sentence-transformers load or 384-dim check failed"; exit 2; }

pass "all-MiniLM-L6-v2 loaded; returns 384-dim vector"

# --- Step 3: SQLite FTS5 with pinned interpreter ---
step_header 3 "SQLite FTS5 via pinned Python"

"$WASHING_MACHINE_PYTHON" -c "
import sqlite3
c = sqlite3.connect(':memory:')
c.execute('CREATE VIRTUAL TABLE t USING fts5(x)')
c.execute('INSERT INTO t VALUES(?)', ('doctor phone urology',))
row = c.execute('SELECT * FROM t WHERE t MATCH ?', ('doctor',)).fetchone()
assert row is not None, 'fts5 query returned no rows'
assert 'doctor' in row[0]
print('fts5 query ok')
" || { fail "SQLite FTS5 not available in pinned Python"; exit 3; }

pass "SQLite FTS5 works with $WASHING_MACHINE_PYTHON"

# --- Step 4: MiniMax chat smoke via minimax-json-job.sh ---
step_header 4 "MiniMax chat smoke (minimax-json-job.sh)"

if [[ -z "${MINIMAX_API_KEY:-}" ]]; then
  if [[ -f "$HOME/.zshrc" ]]; then
    set +u
    # shellcheck disable=SC1091
    source "$HOME/.zshrc" >/dev/null 2>&1 || true
    set -u
  fi
fi

if [[ -z "${MINIMAX_API_KEY:-}" ]]; then
  fail "MINIMAX_API_KEY not set in environment. Check ~/.zshrc."
  exit 4
fi

# Write trivial system prompt to tempfile (--prompt-stdin + --input - is rejected
# by the wrapper at scripts/minimax-json-job.sh:92-95 -- see plan D-note).
cat > "$TEST_PROMPT" <<'EOF'
Return exactly this JSON and nothing else (no fences, no prose): {"ok": true}
EOF

MINIMAX_JOB="${REPO_ROOT}/scripts/minimax-json-job.sh"
if [[ ! -x "$MINIMAX_JOB" ]]; then
  fail "scripts/minimax-json-job.sh not found or not executable at $MINIMAX_JOB"
  exit 4
fi

info "Calling MiniMax-M2.7 via $MINIMAX_JOB (timeout 30s, wrapper: ${TIMEOUT_CMD:-<none>})"
STDERR_FILE=$(mktemp)
set +e
RESP=$(echo "hello" | run_with_timeout 30 "$MINIMAX_JOB" \
  --prompt "$TEST_PROMPT" \
  --input - \
  --job-name preflight-smoke \
  --model MiniMax-M2.7 2>"$STDERR_FILE")
RC=$?
set -e

if [[ $RC -ne 0 ]]; then
  fail "MiniMax chat smoke failed (rc=$RC)"
  fail "stderr: $(cat "$STDERR_FILE")"
  rm -f "$STDERR_FILE"
  exit 4
fi
rm -f "$STDERR_FILE"

if ! echo "$RESP" | jq -e '.ok == true' >/dev/null 2>&1; then
  fail "MiniMax response not the expected {\"ok\": true}. Got: $RESP"
  exit 4
fi

pass "MiniMax-M2.7 chat reachable; returned valid JSON within timeout"

# --- Step 5: MiniMax VLM smoke (POST /v1/coding_plan/vlm) ---
step_header 5 "MiniMax VLM smoke (coding-plan-vlm)"

# Generate a tiny 1x1 PNG inline if no fixture exists -- enough to prove the endpoint
# responds. Real OCR accuracy is gated in Commit 3's extract-attachment.test.sh.
if [[ ! -f "$TEST_IMAGE" ]]; then
  info "Generating minimal test PNG at $TEST_IMAGE"
  "$WASHING_MACHINE_PYTHON" -c "
import base64
# Known-valid 1x1 white PNG (67 bytes)
png_b64 = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkAAIAAAoAAv/lxKUAAAAASUVORK5CYII='
with open('$TEST_IMAGE', 'wb') as f:
    f.write(base64.b64decode(png_b64))
print('generated 1x1 test PNG')
" || { fail "test PNG generation failed"; exit 5; }
fi

B64=$(base64 < "$TEST_IMAGE" | tr -d '\n')
# macOS 'file' reports valid image/png; stays canonical for preflight
MIME=$(file -b --mime-type "$TEST_IMAGE")

info "POST /v1/coding_plan/vlm on api.minimaxi.com (timeout 30s)"
VLM_STDERR=$(mktemp)
set +e
VLM_RESP=$(curl --max-time 30 -sS \
  "https://api.minimaxi.com/v1/coding_plan/vlm" \
  -H "Authorization: Bearer ${MINIMAX_API_KEY}" \
  -H "MM-API-Source: K2B" \
  -H "Content-Type: application/json" \
  -d "$(jq -n \
    --arg p "Describe this image in one short sentence." \
    --arg img "data:${MIME};base64,${B64}" \
    '{prompt: $p, image_url: $img}')" 2>"$VLM_STDERR")
VLM_RC=$?
set -e

if [[ $VLM_RC -ne 0 ]]; then
  fail "VLM HTTP call failed (rc=$VLM_RC)"
  fail "stderr: $(cat "$VLM_STDERR")"
  rm -f "$VLM_STDERR"
  fail "If rc=28 (timeout) or 22 (HTTP 4xx), check:"
  fail "  - API key is .com-minted (not .io): echo \$MINIMAX_API_KEY | head -c 10"
  fail "  - Host resolves: dig api.minimaxi.com"
  fail "  - Account has real-name verification if base_resp.status_code == 2038"
  exit 5
fi
rm -f "$VLM_STDERR"

# Guard: VLM must return valid JSON. Non-JSON HTTP 200 body (e.g., HTML error page
# from an upstream proxy, or rate-limit page) would otherwise kill the script via
# `set -e` mid-jq with no error message.
if ! echo "$VLM_RESP" | jq -e . >/dev/null 2>&1; then
  fail "VLM returned HTTP 200 but body is not valid JSON. First 500 chars:"
  fail "$(echo "$VLM_RESP" | head -c 500)"
  exit 5
fi

VLM_STATUS=$(echo "$VLM_RESP" | jq -r '.base_resp.status_code // "missing"')
VLM_CONTENT=$(echo "$VLM_RESP" | jq -r '.content // ""')

if [[ "$VLM_STATUS" != "0" ]]; then
  VLM_MSG=$(echo "$VLM_RESP" | jq -r '.base_resp.status_msg // "no message"')
  fail "VLM returned non-zero status_code: $VLM_STATUS ($VLM_MSG)"
  fail "Error code reference:"
  fail "  1002 = rate limit (retry after window)"
  fail "  1004 = auth / region mismatch (check .com vs .io)"
  fail "  1008 = quota exhausted"
  fail "  2038 = real-name verification required"
  exit 5
fi

if [[ -z "$VLM_CONTENT" ]]; then
  fail "VLM returned status_code=0 but empty content field. Full response:\n$VLM_RESP"
  exit 5
fi

pass "VLM endpoint reachable; status_code=0; content non-empty (${#VLM_CONTENT} chars)"

# --- Step 6: flock / mkdir dual lock pattern ---
step_header 6 "flock / mkdir dual lock pattern"

# Copy the pattern from motivations-helper.sh
rm -rf "$LOCK_DIR" "${LOCK_DIR}.d" 2>/dev/null || true

if command -v flock >/dev/null 2>&1; then
  info "flock available -- testing flock path"
  exec 9>"$FLOCK_LOCKFILE"
  if ! flock -x -w 2 9; then
    fail "flock acquisition failed"
    exit 6
  fi
  flock -u 9
  exec 9>&-
  pass "flock path works"
else
  info "flock not available -- testing mkdir fallback path"
  if ! mkdir "${LOCK_DIR}.d"; then
    fail "mkdir lock acquire failed"
    exit 6
  fi
  rmdir "${LOCK_DIR}.d"
  pass "mkdir fallback path works (expected on macOS without brew-install flock)"
fi

# --- Step 7: vault-query.sh search for Dr Lo ---
step_header 7 "Obsidian REST via vault-query.sh"

VAULT_QUERY="${REPO_ROOT}/scripts/vault-query.sh"
if [[ ! -x "$VAULT_QUERY" ]]; then
  fail "scripts/vault-query.sh not found or not executable at $VAULT_QUERY"
  exit 7
fi

if [[ -z "${OBSIDIAN_API_KEY:-}" ]]; then
  if [[ -f "$HOME/.zshrc" ]]; then
    set +u
    # shellcheck disable=SC1091
    source "$HOME/.zshrc" >/dev/null 2>&1 || true
    set -u
  fi
fi

if [[ -z "${OBSIDIAN_API_KEY:-}" ]]; then
  fail "OBSIDIAN_API_KEY not set. Check ~/.zshrc or ~/.config/k2b/."
  exit 7
fi

info "Searching vault for 'Dr Lo Hak Keung' (timeout 10s, wrapper: ${TIMEOUT_CMD:-<none>})"
VAULT_STDERR=$(mktemp)
set +e
VAULT_RESP=$(run_with_timeout 10 "$VAULT_QUERY" search "Dr Lo Hak Keung" 2>"$VAULT_STDERR")
VAULT_RC=$?
set -e

if [[ $VAULT_RC -ne 0 ]]; then
  fail "vault-query.sh failed (rc=$VAULT_RC)"
  fail "stderr: $(cat "$VAULT_STDERR")"
  fail "Check that Obsidian is running on the Mac Mini with the Local REST API plugin enabled."
  rm -f "$VAULT_STDERR"
  exit 7
fi
rm -f "$VAULT_STDERR"

HIT_COUNT=$(echo "$VAULT_RESP" | jq -r 'length // 0' 2>/dev/null || echo "0")
if [[ "$HIT_COUNT" -eq 0 ]]; then
  fail "vault-query.sh returned zero results for 'Dr Lo Hak Keung'. Expected person page + Daily note to be indexed."
  exit 7
fi

pass "Obsidian REST reachable; found $HIT_COUNT result(s) for 'Dr Lo Hak Keung'"

# --- Summary ---
echo
echo "${GREEN}===================================${RESET}"
echo "${GREEN}All 7 preflight checks passed.${RESET}"
echo "${GREEN}===================================${RESET}"
echo "WASHING_MACHINE_PYTHON = $WASHING_MACHINE_PYTHON"
echo "env file              = $ENV_FILE"
echo
echo "Next: Commit 0 ready to stage. Move to Commit 0b (calibration corpus + fixtures)."
