#!/usr/bin/env python3
"""Convert browser-extension JSON cookies to a yt-dlp Netscape cookie file."""

from __future__ import annotations

import json
import os
import stat
import sys
import tempfile
from pathlib import Path
from typing import Any

ALLOWED_DOMAINS = {
    "youtube.com",
    "youtube-nocookie.com",
    "googlevideo.com",
}


def usage() -> None:
    print(
        "Usage: yt-cookies-json-to-netscape.py <cookies.json> <youtube-cookies.txt>",
        file=sys.stderr,
    )
    raise SystemExit(1)


def as_bool(value: Any) -> bool:
    if isinstance(value, bool):
        return value
    if isinstance(value, str):
        return value.lower() in {"1", "true", "yes"}
    return bool(value)


def safe_field(cookie: dict[str, Any], field: str, index: int) -> str:
    value = cookie.get(field)
    if value is None:
        raise ValueError(f"cookie #{index} is missing {field}")
    text = str(value)
    if "\t" in text or "\n" in text or "\r" in text:
        name = str(cookie.get("name", "<unnamed>"))
        raise ValueError(f"cookie #{index} ({name}) has unsupported control chars in {field}")
    return text


def expiration(cookie: dict[str, Any]) -> int:
    if as_bool(cookie.get("session")) or cookie.get("expirationDate") in (None, ""):
        return 0
    return int(float(cookie["expirationDate"]))


def allowed_domain(domain: str) -> bool:
    normalized = domain.lstrip(".").lower()
    return normalized in ALLOWED_DOMAINS or any(
        normalized.endswith(f".{allowed}") for allowed in ALLOWED_DOMAINS
    )


def cookie_line(cookie: dict[str, Any], index: int) -> str:
    domain = safe_field(cookie, "domain", index)
    path = str(cookie.get("path") or "/")
    if "\t" in path or "\n" in path or "\r" in path:
        name = str(cookie.get("name", "<unnamed>"))
        raise ValueError(f"cookie #{index} ({name}) has unsupported control chars in path")

    include_subdomains = "TRUE" if domain.startswith(".") or cookie.get("hostOnly") is False else "FALSE"
    secure = "TRUE" if as_bool(cookie.get("secure")) else "FALSE"
    name = safe_field(cookie, "name", index)
    value = safe_field(cookie, "value", index)

    return "\t".join(
        [
            domain,
            include_subdomains,
            path,
            secure,
            str(expiration(cookie)),
            name,
            value,
        ]
    )


def filter_cookies(cookies: list[dict[str, Any]]) -> list[dict[str, Any]]:
    filtered: list[dict[str, Any]] = []
    for cookie in cookies:
        domain = cookie.get("domain")
        if isinstance(domain, str) and allowed_domain(domain):
            filtered.append(cookie)
    return filtered


def load_cookies(path: Path) -> list[dict[str, Any]]:
    with path.open("r", encoding="utf-8") as handle:
        data = json.load(handle)
    if isinstance(data, dict) and isinstance(data.get("cookies"), list):
        data = data["cookies"]
    if not isinstance(data, list):
        raise ValueError("cookie JSON must be a list or an object with a cookies list")
    cookies: list[dict[str, Any]] = []
    for index, item in enumerate(data, start=1):
        if not isinstance(item, dict):
            raise ValueError(f"cookie #{index} is not an object")
        cookies.append(item)
    return cookies


def write_cookie_file(cookies: list[dict[str, Any]], output: Path) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by K2B yt-cookies-json-to-netscape.py. Do not commit.",
    ]
    lines.extend(cookie_line(cookie, index) for index, cookie in enumerate(cookies, start=1))
    payload = "\n".join(lines) + "\n"

    fd, tmp_path = tempfile.mkstemp(prefix=f".{output.name}.", dir=str(output.parent))
    try:
        os.fchmod(fd, stat.S_IRUSR | stat.S_IWUSR)
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(payload)
        os.replace(tmp_path, output)
        os.chmod(output, stat.S_IRUSR | stat.S_IWUSR)
    except Exception:
        try:
            os.unlink(tmp_path)
        except FileNotFoundError:
            pass
        raise


def main(argv: list[str]) -> int:
    if len(argv) != 3:
        usage()
    input_path = Path(argv[1]).expanduser()
    output_path = Path(argv[2]).expanduser()

    cookies = filter_cookies(load_cookies(input_path))
    write_cookie_file(cookies, output_path)
    print(f"Converted {len(cookies)} cookies to {output_path}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main(sys.argv))
    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        raise SystemExit(1)
